### ISSUE TITLE
Possible packaging error for `scipy`

### ISSUE THREAD

**Issue by elac-safran** [emscripten-forge/recipes#2031]
A project of mine relies on an environment defined with:

```yaml
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas
  - jsonschema
  - numpy>1.12
  - scipy
  - jinja2
  - plotly
  - nbformat
```

The environment is created with no problem. However, it installs `numpy` 2.2 and `scipy` 1.11, which are incompatible (https://docs.scipy.org/doc/scipy/dev/toolchain.html#numpy).

The list given in the link stops at version 1.13.
I know for a fact that `scipy` 1.15 is compatible with `numpy` 2; I do not know for v1.14.

At any rate, there seems to be a possible packaging error in the repository.
Could you please look into it?
