### ISSUE TITLE
Cannot import `Voronoi` from `scipy.spatial`

### ISSUE THREAD

**Issue by jeertmans** [emscripten-forge/recipes#624]
Hello,

I'm trying to import `Voronoi` from `scipy.spatial` but it does not work, see the error message.

![image](https://github.com/emscripten-forge/recipes/assets/27275099/f206eee7-dbdb-4a0b-b341-801343042f43)

My `environment.yml`:

```yaml
name: xeus-python-kernel  
channels:  
- https://repo.mamba.pm/emscripten-forge  
- https://repo.mamba.pm/conda-forge  
dependencies:  
- ipympl  
- matplotlib>=3,<4  
- numpy>=1.24,<1.25  
- scipy==1.8.1
```

and SciPy is correctly installed from your channel:

```
scipy              emscripten-forge/emscripten-32::scipy-1.8.1-py310h74ff0a5_4
```

I have tried clearing the cache, but this does not solve the issue.

I took a quick look at https://github.com/emscripten-forge/recipes/tree/main/recipes/recipes_emscripten/scipy, and it does not seem that `Voronoi` was removed from SciPy.

Locally, when `scipy==1.8.1` on Python 3.10, I can import it with success:

```python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.spatial import Voronoi
>>> import scipy;scipy.__version__
'1.8.1'
```

> NOTE: I am using JupyterLite, and the corresponding repository can be found [here](https://github.com/jeertmans/LELEC2796).
