### ISSUE TITLE
(emscripten-forge channel) "package does not exist"

### ISSUE THREAD

**Issue by michaelweinold** [emscripten-forge/recipes#714]
...now that I was able to resolve https://github.com/emscripten-forge/recipes/issues/695, I can't seem to install certain packages from the emscripten-forge channel:

```yaml
name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - pandas=1.5.3 # https://beta.mamba.pm/channels/emscripten-forge/packages/pandas
  - numpy=1.25.2 # https://beta.mamba.pm/channels/emscripten-forge/packages/numpy
  - scipy=1.11.1 # https://beta.mamba.pm/channels/emscripten-forge/packages/scipy
  # BRIGHTWAY DEPENDENCIES (NOT PURE PYTHON)
  - peewee=3.17.0 # https://beta.mamba.pm/channels/emscripten-forge/packages/peewee
  - lxml=4.9.3 # https://beta.mamba.pm/channels/emscripten-forge/packages/lxml
```

returns

```
[LiteBuildApp] No archive (yet): xeus-python-demo-jupyterlite.tgz
[LiteBuildApp]     jupyter-lite.(json|ipynb): 0 files
/home/runner/micromamba/envs/build-env/lib/python3.12/site-packages/jupyterlite_core/addons/base.py:294: UserWarning: install libarchive-c for better perfomance when working with archives: No module named 'libarchive'
  return has_optional_dependency(
/home/runner/micromamba/envs/build-env/lib/python3.12/site-packages/jupyterlite_core/addons/translation.py:88: UserWarning: [lite] [translation] install `jupyterlab_server` to load translations: No module named 'jupyterlab_server'
  if not self.is_sys_prefix_ignored() and has_optional_dependency(
error    libmamba ZSTD decompression error: Unknown frame descriptor
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ lxml 4.9.3**  does not exist (perhaps a typo or a missing channel);
    └─ peewee 3.17.0**  does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```
