### ISSUE TITLE
Drop `requests-wasm-polyfill`?

### ISSUE THREAD

**Issue by jtpio** [emscripten-forge/recipes#782]
Looking at the latest release of `urllib3`: https://github.com/urllib3/urllib3/releases/tag/2.2.0

It looks like we might be able to drop `requests-wasm-polyfill`, since they now seem to be supporting `emscripten` (not just Pyodide) as an environment, and `requests` depends on `urllib3`.

cc @DerThorsten who may also have some insights on this.

**Comment by jtpio** [comment]
Trying this locally quickly, maybe this would first require to package `brotli`?

![image](https://github.com/emscripten-forge/recipes/assets/591645/6faf76f4-1265-4722-b724-042bc86306ae)


Using this test `environment.yml`:

```yaml
name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - requests
  - urllib3 >=2.2.0
```
